#!/bin/bash
# GLM-4.6 (MoE) — 10 nodes × 8 H100s = 80 GPUs, disaggregated (P2P), Megatron.
MODEL_PATH=zai-org/GLM-4.6
NUM_NODES=10
HYBRID_ENGINE=False

TENSOR_MODEL_PARALLEL_SIZE=8
EXPERT_MODEL_PARALLEL_SIZE=8
PIPELINE_MODEL_PARALLEL_SIZE=8
SAMPLER_TENSOR_MODEL_PARALLEL_SIZE=16
SAMPLER_TRAINER_GPU_RATIO=0.25

GPU_MEMORY_UTILIZATION=0.70

source "$(dirname "$0")/_common.sh"
