#!/bin/bash
# GPT-OSS-20B (MoE, softcap attention) — 1 node × 8 H100s, hybrid, Megatron.
MODEL_PATH=unsloth/gpt-oss-20b-BF16
NUM_NODES=1
HYBRID_ENGINE=True

TENSOR_MODEL_PARALLEL_SIZE=2
PIPELINE_MODEL_PARALLEL_SIZE=2
SAMPLER_TENSOR_MODEL_PARALLEL_SIZE=4

ACTOR_MAX_TOKEN_LEN=16384
INFER_MAX_TOKEN_LEN=16384
GPU_MEMORY_UTILIZATION=0.8

source "$(dirname "$0")/_common.sh"
