#!/bin/bash
# GLM-4.6 (MoE) — 10 nodes × 8 H100s = 80 GPUs, hybrid, Megatron.
MODEL_PATH=zai-org/GLM-4.6
NUM_NODES=10
HYBRID_ENGINE=True

TENSOR_MODEL_PARALLEL_SIZE=8
EXPERT_MODEL_PARALLEL_SIZE=8
PIPELINE_MODEL_PARALLEL_SIZE=10
SAMPLER_TENSOR_MODEL_PARALLEL_SIZE=16

GPU_MEMORY_UTILIZATION=0.70

source "$(dirname "$0")/_common.sh"
