#!/bin/bash
# Qwen3-235B-A22B (MoE) — 8 nodes × 8 H100s = 64 GPUs, disaggregated (P2P), Megatron.
MODEL_PATH=Qwen/Qwen3-235B-A22B
NUM_NODES=8
HYBRID_ENGINE=False

TENSOR_MODEL_PARALLEL_SIZE=4
EXPERT_MODEL_PARALLEL_SIZE=4
PIPELINE_MODEL_PARALLEL_SIZE=12
SAMPLER_TENSOR_MODEL_PARALLEL_SIZE=8
SAMPLER_TRAINER_GPU_RATIO=0.33

ACTOR_MAX_TOKEN_LEN=24576
GPU_MEMORY_UTILIZATION=0.85

source "$(dirname "$0")/_common.sh"
