#!/bin/bash
# Qwen3-30B-A3B (MoE) — 1 node × 8 H100s, hybrid engine, Megatron.
MODEL_PATH=Qwen/Qwen3-30B-A3B
NUM_NODES=1
HYBRID_ENGINE=True

TENSOR_MODEL_PARALLEL_SIZE=4
EXPERT_MODEL_PARALLEL_SIZE=4
PIPELINE_MODEL_PARALLEL_SIZE=2
SAMPLER_TENSOR_MODEL_PARALLEL_SIZE=8

source "$(dirname "$0")/_common.sh"
